const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 950 } });
    const errors = [], writes = [];
    const environmentalRequests = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('request', r => { if (r.url().includes('/farms') && r.method() !== 'GET') writes.push(r.url()); });
    page.on('request', r => { if (/\/(buffer|analyze)(\?|$)/.test(r.url())) environmentalRequests.push(r.url()); });
    await page.route('https://fonts.**/**', r => r.abort());
    await page.route('https://unpkg.com/**', r => r.abort());
    await page.route('https://cdnjs.cloudflare.com/**', r => r.abort());
    let imageFails = false;
    await page.route('https://server.arcgisonline.com/**/export?**', r => imageFails ? r.abort() : r.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="#465c35"/></svg>' }));
    const polygon = { type: 'Polygon', coordinates: [[[-88.4,18.7],[-88.39,18.7],[-88.39,18.71],[-88.4,18.7]]] };
    await page.addInitScript(() => sessionStorage.setItem('agtech.demo.session', 'test-token'));
    await page.route('**/providers/me', r => r.fulfill({ json: { providerId: 'demo-provider-001', nombrePublico: 'Cooperativa Demo TerraSync' } }));
    let mode = 'full';
    await page.route('**/providers/me/farms', r => r.fulfill({ status: mode === 'error' ? 503 : mode === 'expired' ? 401 : 200,
      json: mode === 'empty' ? [] : [{ farmId: 'demo-farm-001', nombre: 'Parcela Demo Milpa', productor: 'Productor ficticio', historia: '<img src=x onerror=alert(1)>', actividadEconomica: 'Cultivo de maíz', estado: 'Quintana Roo', pais: 'México', esDemostracion: true, geojson: polygon }, { farmId: 'old', nombre: 'Parcela con datos parciales' }] }));
    await page.goto('http://127.0.0.1:8010/proveedor.html');
    await page.locator('.provider-farm').first().waitFor();
    assert.equal(await page.locator('.provider-farm').count(), 2);
    await page.locator('.parcel-preview.ready').waitFor();
    async function checkLayout() {
      const name = await page.locator('.provider-farm-name').first().boundingBox();
      const label = await page.locator('.expand-label').first().boundingBox();
      const image = await page.locator('.parcel-preview').first().boundingBox();
      assert.ok(label.y >= name.y + name.height);
      assert.ok(image.x >= name.x + name.width);
    }
    await checkLayout();
    assert.equal(await page.locator('.expand-label').first().textContent(), 'Mostrar información');
    await page.locator('summary').first().click();
    await page.getByText('Ocultar información', { exact: true }).waitFor();
    assert.equal(await page.locator('.provider-farm img').count(), 1);
    assert.equal(await page.locator('.farm-story img').count(), 0);
    assert.equal(await page.getByRole('link', { name: 'Ver perfil público y análisis disponible' }).first().getAttribute('href'), '/parcela.html?id=demo-farm-001&vista=proveedor');
    await page.locator('summary').first().focus(); await page.keyboard.press('Enter');
    assert.equal(await page.locator('details').first().getAttribute('open'), null);
    await page.getByRole('button', { name: 'Agregar parcela', exact: true }).click();
    await page.waitForURL('**/agregar-parcela.html');
    await page.getByRole('link', { name: 'Mis parcelas' }).click();
    await page.locator('.provider-farm').first().waitFor();
    if (process.env.DASHBOARD_SCREENSHOT) await page.screenshot({ path: process.env.DASHBOARD_SCREENSHOT, fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await checkLayout();
    await page.locator('summary').first().click();
    if (process.env.DASHBOARD_MOBILE_SCREENSHOT) await page.screenshot({ path: process.env.DASHBOARD_MOBILE_SCREENSHOT, fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    imageFails = true; await page.reload();
    await page.getByText('No se pudo cargar la vista satelital', { exact: true }).waitFor();
    await page.locator('summary').first().click();
    await page.getByRole('link', { name: 'Ver perfil público y análisis disponible' }).first().waitFor();
    mode = 'empty'; await page.reload();
    await page.getByText('Todavía no tienes parcelas asociadas.', { exact: false }).waitFor();
    mode = 'error'; await page.reload();
    await page.locator('#farms-retry:not([hidden])').waitFor();
    mode = 'full'; await page.locator('#farms-retry').click();
    await page.locator('.provider-farm').first().waitFor();
    mode = 'expired'; await page.reload();
    await page.waitForURL('**/acceso.html');
    assert.deepEqual(errors, []);
    assert.deepEqual(writes, []);
    assert.deepEqual(environmentalRequests, []);
    console.log('OK: listado, desplegables, perfil, aviso de alta, móvil, vacío, error, reintento, sesión vencida y solo lectura.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
